services:
  - type: web
    name: election-monitor-command-center
    runtime: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATA_FILE
        value: /tmp/data.json
      - key: EVIDENCE_STORAGE_DIR
        value: /tmp/evidence
      - key: JWT_SECRET
        generateValue: true
      - key: IREV_AUTO_SYNC
        value: "false"
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_EMAIL
        value: admin@command.local
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: SUPER_ADMIN_EMAIL
        value: superadmin@command.local
      - key: SUPER_ADMIN_PASSWORD
        generateValue: true
      - key: CLOUDFLARE_TURN_KEY_ID
        sync: false
      - key: CLOUDFLARE_TURN_API_TOKEN
        sync: false
      - key: CLOUDFLARE_TURN_TTL
        value: "86400"
      - key: EXPRESSTURN_URLS
        sync: false
      - key: EXPRESSTURN_USERNAME
        sync: false
      - key: EXPRESSTURN_PASSWORD
        sync: false
